
# This is your Supabase project configuration

project_id = "tokybrabdqqahhbxxpzj"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

# Correctly formatted functions configuration
[functions]
# Define the port as an integer directly (not nested)
port = 54321

# Correctly define CORS as its own section
[functions.http.cors]
allowedOrigins = ["*"]
allowedMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowedHeaders = ["authorization", "x-client-info", "apikey", "content-type"]
exposedHeaders = ["authorization", "x-client-info", "apikey", "content-type"]
