
# The project ID of your Supabase project
project_id = "tokybrabdqqahhbxxpzj"

[functions.realtime-transcription-token]
verify_jwt = false
max_retries = 0

[functions.process-text]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
