
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokybrabdqqahhbxxpzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva3licmFiZHFxYWhoYnh4cHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwODQ0OTMsImV4cCI6MjA1NzY2MDQ5M30.VEUZyulxKhMS3JLtCPnzWaFo8ouJzvMoU5HLneq0Dos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'ortho-care-auth-token',
      detectSessionInUrl: false, // Changed from true to false to prevent automatic URL-based session changes
      flowType: 'pkce', // More secure flow type
    },
    global: {
      headers: {
        'x-app-name': 'ortho-care-mosaic',
      },
    },
  }
);

// Add debug logging for auth state changes with more detailed information
supabase.auth.onAuthStateChange((event, session) => {
  console.log(`Supabase Auth State Changed: ${event}`, session ? session.user?.id : 'No user', {
    event,
    userId: session?.user?.id,
    timestamp: new Date().toISOString(),
  });
});

// Enhanced helper function to clear Supabase session and local storage
export const clearAuthState = async () => {
  try {
    console.log('Attempting to clear auth state...');
    
    // Sign out from Supabase with explicit scope
    const { error } = await supabase.auth.signOut({ scope: 'global' }); // Changed from 'local' to 'global' for complete signout
    
    if (error) {
      throw error;
    }
    
    // Clear the specific auth storage
    window.localStorage.removeItem('ortho-care-auth-token');
    
    // Clear any other auth-related items in local storage
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.includes('supabase') || key.includes('auth') || key.includes('token'))) {
        keysToRemove.push(key);
      }
    }
    
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    console.log('Auth state cleared successfully', { keysRemoved: keysToRemove });
    return { success: true, keysRemoved: keysToRemove };
  } catch (error) {
    console.error('Error clearing auth state:', error);
    return { success: false, error };
  }
};

// Helper for checking DB connection status
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('doctors').select('count(id)', { count: 'exact', head: true });
    if (error) {
      throw error;
    }
    return { connected: true, message: 'Connected to Supabase successfully' };
  } catch (error) {
    console.error('Supabase connection error:', error);
    return { connected: false, message: 'Error connecting to Supabase', error };
  }
};
