
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokybrabdqqahhbxxpzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva3licmFiZHFxYWhoYnh4cHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwODQ0OTMsImV4cCI6MjA1NzY2MDQ5M30.VEUZyulxKhMS3JLtCPnzWaFo8ouJzvMoU5HLneq0Dos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
      storageKey: 'ortho-care-auth',
      detectSessionInUrl: true,
      flowType: 'implicit',
      debug: true,
    },
    global: {
      headers: {
        'x-app-name': 'ortho-care-mosaic',
      },
    },
  }
);

// Add debug logging for auth state changes
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase Auth State Changed:', event, session?.user?.id || 'No user');
});

// Helper for checking DB connection status
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('doctors').select('count(id)', { count: 'exact', head: true });
    if (error) {
      throw error;
    }
    return { connected: true, message: 'Connected to Supabase successfully' };
  } catch (error) {
    console.error('Supabase connection error:', error);
    return { connected: false, message: 'Error connecting to Supabase', error };
  }
};
